02/25/2025 17:09:48 - INFO - __main__ - ***** Running training *****
02/25/2025 17:09:48 - INFO - __main__ -   Num examples = 1221
02/25/2025 17:09:48 - INFO - __main__ -   Num Epochs = 50
02/25/2025 17:09:48 - INFO - __main__ -   Instantaneous batch size per device = 1
02/25/2025 17:09:48 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 4
02/25/2025 17:09:48 - INFO - __main__ -   Gradient Accumulation steps = 4
02/25/2025 17:09:48 - INFO - __main__ -   Total optimization steps = 15000
Steps:   0%|                                                                                                                                                                                          | 0/15000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_test.py", line 975, in <module>
    main()
  File "train_test.py", line 788, in main
    for step, batch in enumerate(train_dataloader):
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/accelerate/data_loader.py", line 550, in __iter__
    current_batch = next(dataloader_iter)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2766, in __getitems__
    batch = self.__getitem__(keys)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2762, in __getitem__
    return self._getitem(key)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/arrow_dataset.py", line 2747, in _getitem
    formatted_output = format_table(
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/formatting/formatting.py", line 639, in format_table
    return formatter(pa_table, query_type=query_type)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/formatting/formatting.py", line 407, in __call__
    return self.format_batch(pa_table)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/formatting/formatting.py", line 521, in format_batch
    batch = self.python_features_decoder.decode_batch(batch)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/formatting/formatting.py", line 228, in decode_batch
    return self.features.decode_batch(batch) if self.features else batch
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/features/features.py", line 2087, in decode_batch
    [
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/features/features.py", line 2088, in <listcomp>
    decode_nested_example(self[column_name], value, token_per_repo_id=token_per_repo_id)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/features/features.py", line 1405, in decode_nested_example
    return schema.decode_example(obj, token_per_repo_id=token_per_repo_id)
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/datasets/features/image.py", line 189, in decode_example
    if image.getexif().get(PIL.Image.ExifTags.Base.Orientation) is not None:
  File "/home/jinxulin/anaconda3/envs/miss/lib/python3.8/site-packages/PIL/Image.py", line 65, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'ExifTags'
